// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "layouts/root.tsx": {
    id: "layouts/root";
    page: "/";
  };
  "layouts/site.tsx": {
    id: "layouts/site";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/root": typeof import("./app/layouts/root.tsx");
  "layouts/site": typeof import("./app/layouts/site.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
};